spring:
  application:
    name: pet-mgmt-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/sd
    username: postgres
    password: Luisa211003
  flyway:
    enabled: false
    locations:
      - classpath:db/migration
      - classpath:db/data
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  swagger-ui:
    enabled: true
security:
  secret-key: PS-SD-2025-30432-1q2w3e4r5t6y7u8i9o0p
  token-expiration-days: 15
server:
  port: 8777
  servlet:
    context-path: '/api'
logging:
  level:
    root: INFO
    sd.project.demo: INFO
